/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2ac7e41d-842e-4fb9-bbe2-2cb8f9c4ddd6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_cbtboMf9q",
    "aws_user_pools_web_client_id": "7cg1mobmmo3drr9p63ieq5btke",
    "oauth": {}
};


export default awsmobile;
